- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/ekf_robot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/ground_truth/odom_raw"
  gz_topic_name: "/model/ekf_robot/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
